### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when execute `FamilyRunner`

### ISSUE THREAD

**Issue by Steve-Lee-DG** [databrickslabs/automl-toolkit#5]
Hi 
I got an Error : java.lang.ArrayIndexOutOfBoundsException: 1 when i execute the `FamilyRunner`
 or `AutomationRunner`
I used the practice example in `README.md`.
How can i solve this problem?
```
val data = spark.table("DF")

val overrides = Map("labelCol" -> "class")

val randomForestConfig = ConfigurationGenerator.generateConfigFromMap("RandomForest", "classifier", overrides)
val gbtConfig = ConfigurationGenerator.generateConfigFromMap("GBT", "classifier", overrides)
val logConfig = ConfigurationGenerator.generateConfigFromMap("LogisticRegression", "classifier", overrides)


val runner = FamilyRunner(data, Array(randomForestConfig, gbtConfig, logConfig))..execute()
```

And Error code is below :

```

ava.lang.ArrayIndexOutOfBoundsException: 1
	at com.databricks.labs.automl.utils.WorkspaceDirectoryValidation.validate(WorkspaceDirectoryValidation.scala:96)
	at com.databricks.labs.automl.utils.WorkspaceDirectoryValidation$.apply(WorkspaceDirectoryValidation.scala:123)
	at com.databricks.labs.automl.executor.DataPrep.prepData(DataPrep.scala:275)
	at com.databricks.labs.automl.executor.FamilyRunner$$anonfun$execute$1.apply(FamilyRunner.scala:125)
	at com.databricks.labs.automl.executor.FamilyRunner$$anonfun$execute$1.apply(FamilyRunner.scala:119)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.databricks.labs.automl.executor.FamilyRunner.execute(FamilyRunner.scala:119)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-983:1)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-983:48)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$$iw$$iw$$iw$$iw.<init>(command-983:50)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$$iw$$iw$$iw.<init>(command-983:52)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$$iw$$iw.<init>(command-983:54)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$$iw.<init>(command-983:56)
	at line3fa913e91f964622bbee0641bf7664fb138.$read.<init>(command-983:58)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$.<init>(command-983:62)
	at line3fa913e91f964622bbee0641bf7664fb138.$read$.<clinit>(command-983)
	at line3fa913e91f964622bbee0641bf7664fb138.$eval$.$print$lzycompute(<notebook>:7)
	at line3fa913e91f964622bbee0641bf7664fb138.$eval$.$print(<notebook>:6)
	at line3fa913e91f964622bbee0641bf7664fb138.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:679)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:632)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:368)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:345)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:271)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:345)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by BenWilson2** [comment]
Hi Steve, this is due to not specifying a valid Workspace path in your mlflow Experiment name... 
the experiment name should be something like this:
/Users/ben@databricks.com/AutoML/MyCoolProject/logging
By default, the path provided attempts to write to the root workspace path, which your account likely doesn't have permissions to do so.  Either create a root Workspace folder that has appropriate permissions (an admin will have to do this) OR write to your user directory pathing.
Also - with the next release (0.6.0), there will be a custom exception thrown that explains this problem without having to do stack trace digging.
Thank you for the heads-up on this issue!

**Comment by Steve-Lee-DG** [comment]
It looks like working!! 
Thank you.
